### ISSUE TITLE
PAT check for mail automatically

### ISSUE THREAD

**Issue by toddejohnson** [toddejohnson/rmspi#1]
Need a configurable cron job for PAT to check for mail automatically. Need to be able to configure:

- time
- remote to check with(telnet, url, or alias)

**Comment by martinhpedersen** [comment]
Hi,

you should check out the `schedule` config parameter:

```json
{
  "schedule": {
    "*/10 * * * *": "connect ax25://FOOBAR?freq=1234"
  }
}
```
The [docs](https://godoc.org/github.com/la5nta/pat/cfg#Config) are outdated, but you can schedule all interactive commands this way.

By allowing the Pat http daemon to control the scheduling, you will avoid race conditions and log truncation.

Just a friendly suggestion!

-- 
73 de LA5NTA/Martin

**Comment by toddejohnson** [comment]
@martinhpedersen Thank you for the suggestion! I'll implement it that way.
