### ISSUE TITLE
Add ability to change baud rate from rmspi.txt

### ISSUE THREAD

**Issue by dsrawding** [toddejohnson/rmspi#6]
I have been using the image with tnc's other than the tnc-x.  The only issue is that most older tnc's don't go over 9600 baud.  So when the image boots I have to stop kissattach, change the baud rate in axports and run kissattach again.  Is there a way to add the baud rate to rmspi.txt or to not have axports overwritten each time?  Thanks for the great product!

**Comment by dsrawding** [comment]
Found where it is set in ax25-up.  I'll set it there, sorry for the request.

**Comment by toddejohnson** [comment]
Sure I think I could just add it to the script. Where does it need changed? Just the baud in axports? Would you feel comfortable making a pull request? Should just need a new variable in rmspi.txt that is used in ax25-up.

**Comment by dsrawding** [comment]
Not sure how to do a pull request but all that needs to be done is create the baud variable in rmspi.txt and call it on line 20 of ax25-up.

0       ${CALL}         19200    256     7       Radio - ${FREQ} MHz 
replace 19200 with ${BAUD}?

This one change should make the image work with any KISS capable TNC.
